name: Check Notebooks Output Using nbstripout

on:
  pull_request:
    paths:
      - '**.ipynb'
  push:
    branches:
      - main
    paths:
      - '**.ipynb'
  workflow_dispatch:

jobs:
  check-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Check notebooks are stripped using nbstripout
        uses: kynan/nbstripout@main
        with:
          paths: '**/*.ipynb'
