name: Strip Notebook Outputs

on:
  pull_request:
      paths:
      - '**.ipynb'

permissions: write-all

jobs:
  nbstripout:
    name: run nbstripout on all notebooks and push changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install nbstripout
        run: pip install nbstripout

      - name: Run nbstripout on all notebooks
        env:
            GH_TOKEN: "${{ github.token }}"
        run: |
          find . -name "*.ipynb" -type f -exec nbstripout --drop-empty-cells {} +
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "run nbstripout on all notebooks"
          git push
